### ISSUE TITLE
CEmu Linux Desktop Entry

### ISSUE THREAD

**Issue by mateoconlechuga** [CE-Programming/CEmu#107]

**Comment by alberthdev** [comment]
For CEmu to get a shiny new icon (and a desktop/menu entry), we probably need a .desktop file for Linux. Some inspiration can be drawn from [TilEm](https://sourceforge.net/p/tilem/code/HEAD/tree/trunk/data/desktop/), which also includes a file type association configuration for CEmu roms, programs, variables, etc.

For the desktop file specifically, we need a [category of sorts](https://specifications.freedesktop.org/menu-spec/latest/apa.html#main-category-registry). TilEm uses `Education;Science;Math;System;Emulator;` for its category string, which might work for us...

Icon setup for TilEm can also be found [here](https://sourceforge.net/p/tilem/code/HEAD/tree/trunk/data/icons/). Main documentation for the desktop entry (and various other branches of integration) can be found [here](https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html).

**Comment by alberthdev** [comment]
Did some minor work on this - CEmu now shows up in your menu + some file associations work! (Well, almost work... my system's WINE likes to jump in at times...)

![Menu Integration](http://i.imgur.com/t7gd6dU.png)

![File Manager Integration](http://i.imgur.com/kBOUB26.png)

**Comment by MattWaltz** [comment]
Wow, great work! :D

**Comment by alberthdev** [comment]
@MattWaltz's actual fix for making the icon work is now in - so this branch should pretty much have somewhat complete support for Linux desktop integration. If anyone that knows Linux integration configuration could check my work (ping ping: @debrouxl), we can merge this branch back to master and get this fixed!

**Comment by debrouxl** [comment]
* my first thought was that PREFIX also applies to e.g. MacOS X, and could be moved outside if (linux) { ... }. However, given that the default MacOS X prefix value is different from the Linux one, this would buy us nothing.
* in gui/qt/CEmu.pro, the desktop.path line needs to use $$PREFIX.

For the desktop file specifically, desktop-file-validate, as well as e.g. Lintian, will perform relatively thorough checking. TILP's desktop integration had to be fixed, based on the output of such tools, at multiple points in time. The latest bugfix was contributed by TC01 based on Fedora feedback; other bugfixes shall stem from Andreas B. Mundt's report in December about Lintian producing "I: tilp2: desktop-entry-lacks-keywords-entry usr/share/applications/tilp.desktop" and "W: tilp2: desktop-mime-but-no-exec-code usr/share/applications/tilp.desktop".
I see that TILP's desktop file uses "Categories=Utility;GTK;X-KDE-Utilities-Peripherals;", which is nowhere near as good as TilEm and therefore now CEmu use...

**Comment by adriweb** [comment]
Regarding the committed icons, make sure they went through some kind of PNG optimizer :)

**Comment by alberthdev** [comment]
@debrouxl: thanks for the feedback! Regarding `$$PREFIX` replacement, would `desktop.path` then become `$$PREFIX/share/applications`? (FYI - `desktop.path` is used, but not actually used... `xdg-*` will automatically install files into the system directory! I gave it a path because QMake seems to require it...)

Will definitely take a look at those verification tools - Lintian might be interesting to look at, though that might require some coaxing for it to check CEmu... possibly making a rough package for it to look at!

@adriweb Will do - new PNGs and script will be up in a bit, all compressed losslessly! (I can also compress lossy, if you guys don't mind that.)

For lossless compression, did some [interesting benchmarks](https://github.com/alberthdev/alberthdev-misc/wiki/PNG-Compression-Comparison-(Icons)) for our icons...

**Comment by adriweb** [comment]
@alberthdev how is it going? :)

(Also, nice benchmarks)

**Comment by MattWaltz** [comment]
bumpity bump bump

**Comment by mateoconlechuga** [comment]
Merged in and everything seems to be working fine :) If someone reports an issue this can be reopened if needed. Nice work!
