### ISSUE TITLE
Redesign interface between threads

### ISSUE THREAD

**Issue by MattWaltz** [CE-Programming/CEmu#109]
This needs to be overhauled, it has gotten bloated and unmanageable. Also fix scheduling while you're at it.

**Comment by adriweb** [comment]
`std::condition_variable` will have to be your friend :)
- http://fr.cppreference.com/w/cpp/thread/condition_variable
- http://stackoverflow.com/a/16350623/378298

**Comment by MattWaltz** [comment]
Actually, I think the current system would work quite fine if variables were not crossing threads like they are now. The main emu QThread could simply pause the thread when debugging and whatnot.

**Comment by MattWaltz** [comment]
Pretty much fixed with 6ae5d1c. Just needs testing I guess, and then this can be closed.

**Comment by adriweb** [comment]
Well well well, seems to work fine on Desktop :)

But it completely broke emscripten: :P
 * It'd be nice not to have `debug.c` become `debug.cpp` just because of a condition variable a mutex. These are [available](http://en.cppreference.com/w/c/thread/cnd_wait) in pure C as well (C11 that is).
 * Even when disabling debugging things, it appears to do "nothing", i.e. blank LCD. And I'm not sure what's happening since `cpu_execute()` seems to be running (PC is basically stuck around 0xD18C50). Any idea?

**Comment by MattWaltz** [comment]
C11 stuff isn't available to me and I'm not sure why...

As for the blank LCD, I don't know how it is being updated :P Is there a way I can test emscripten?

**Comment by adriweb** [comment]
Aww, it appears not many stdlibs ship with C11 `threads`, so hum, I'll see if I can just use some preprocessor `#if`s to just "comment out" the thread stuff for emscripten (since it's single-threaded there anyway).
As for the blank LCD, I'm pretty sure the LCD itself isn't the issue, more like a symptom. (FWIW, I'm just calling `lcd_drawframe(buf_lcd_js, &lcd);` from time to time (when the JS requests it)).

Regarding testing emscripten yourself, hm, I can put some new version on the PB when the page is loaded with a special parameter or something... I'll let you know (but there isn't much to see :P)

**Comment by adriweb** [comment]
So with a newer OS/ROM I had, it seems to be getting further, just excruciatingly slow :P
I'll keep poking around...

**Comment by adriweb** [comment]
"solved" with https://github.com/CE-Programming/CEmu/commit/886b83c8a4df0762152ebb138d4bbd27bf69b9af.

**Comment by MattWaltz** [comment]
I wouldn't consider it solved... what should be done to actually fix it? This could easily break again.

**Comment by adriweb** [comment]
Well, unless we can figure out exactly the required alignment "padding" at compile time, I guess we'll have to remove the structs packing, as per @jacobly's suggestion.

**Comment by jacobly0** [comment]
That's what aligned attributes are for. ;)

**Comment by adriweb** [comment]
Hmm right, we should try that first :D
