### ISSUE TITLE
Can't use OS images from TI's website?

### ISSUE THREAD

**Issue by LoganDark** [CE-Programming/CEmu#124]
The file is [`TI84Plus_OS255.8Xu`](https://education.ti.com/eu/software/details/en/B7DADA7FD4AA40CE9D7911B004B8C460/ti84plusoperatingsystem). The emulator completely freezes when I try to load it.

**Comment by jacobly0** [comment]
You cannot currently load oses into CEmu, you have to dump a rom from a real calculator instead using the startup instructions or tilp.

**Comment by adriweb** [comment]
In addition, CEmu is a CE calculator emulator. The link you mentioned is for the classic 84+, which is not for CEmu (take a look at WabbitEmu instead, for instance).

**Comment by LoganDark** [comment]
@jacobly0 I don't have an actual calculator. That's why I'm trying to find an emulator that can actually emulate one.

**Comment by debrouxl** [comment]
For emulating most TI calculators with Flash memory, the fact that you need a dump of (a subset of) a real calculator's boot code to emulate said calculator model is not a limitation of the emulator, it's a consequence of how the calculator's OS works. Either it references data and code from the boot code (TI-Z80 series, TI-eZ80 series), or the OS is decrypted by the boot code (Nspire series). And TI does not officially distribute these models' boot code...
Some TI-Z80 emulators, especially TilEm, use "BootFree", which contains a very small subset of TI's boot code, just enough to make the OS work. In the community, the "OMG we should not distribute even a few bytes from TI's boot code, in case they sue us" hardliners have tended to gain the upper hand over those who favor user convenience, so the BootFree functionality was removed from WabbitEmu and/or some other emulators. TilEm has good emulation abilities and is my favorite choice - definitely not just because it uses libti*.
Still - BootFree has nothing to do with CEmu, which emulates only the TI-eZ80 series :)

The only product line of TI graphing calculators where emulation works well without a copy of the boot code is the TI-68k series. Basically, only emulating the boot code's OS functionality - which very few people have ever needed to do - requires a copy of the boot code of the corresponding calculator model.
