### ISSUE TITLE
The name CEmu is probably misleading

### ISSUE THREAD

**Issue by j-levy** [CE-Programming/CEmu#141]
There is already another emulator called Cemu, for the WiiU.
More information here : http://cemu.info/

**Comment by adriweb** [comment]
This has come up several times already - both projects started (privately or publicly) at about the same time, without knowledge of the other AFAIK. So that's just the way it is...

If you want to get technical, it's "CEmu" vs "Cemu", the case being different, so it's not 100% the same either.
And our name is simply a mix between "CE" and "Emu", since we're emulating CE hardware :)

Still, the readme and/or homepages are pretty clear on what the software are, so I doubt there will be any confusion for users.
