### ISSUE TITLE
Custom keybindings

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#163]
### Minimum requirements

- A single custom keybind mapping, defined in a human-editable config file.
- Detect and disallow a keyboard key from being mapped to multiple calculator keys.

### Bonus requirements

_(Listed in descending order of importance to me)_

- A toggleable keybind edit mode. Upon activation, bind individual keys with a pattern such as: (1) user clicks on a button on the calculator keypad, then (2) user presses a key on the computer keyboard to establish a mapping. Consider pausing emulation and disabling other controls when in keybind edit mode.
- Multiple custom keybind mappings.
- Keybind mapping import/export.

**Comment by zbot473** [comment]
Any news?

**Comment by nic3-14159** [comment]
I might take a look at this and see what I can do

**Comment by mateoconlechuga** [comment]
Because of the requests, I have added custom keybinding support. You can export a current keymap to view the format; it is pretty straightforward. Most of the time you will not need to worry about the mask, modifier, or native information. That's just extra stuff in case you are running on a neat machine.

Anyway, I tried the keypad binding via the gui, and it just didn't look all that good. Plus it's hard with the variance between Qt and native keys to make it actually work. For now, I feel like this issue can be closed.

Exporting keymaps is available through `File > Export > Keypad Mapping`. Keymaps can be imported in the settings under the `Custom` keymap section. I didn't think it was worthwhile putting the path anywhere, but it can be changed by just clicking the `Custom` radio button again.

Hope that someone finds this useful.

**Comment by zbot473** [comment]
Yay!
