### ISSUE TITLE
Scripting front-end(s) on top of the CEmu IPC

### ISSUE THREAD

**Issue by debrouxl** [CE-Programming/CEmu#19]
In issue #17 , alberthdev mentioned Lua scripting for triggering operations on CEmu instances. This is the brainstorming issue for scripting front-ends on top of the IPC (issue #16 ); the technical choices for scripting will depend on (and perhaps slightly influence ?) the choices for the IPC mechanism.

**Comment by MateoConLechuga** [comment]
Reopened because brainstorming never hurts :D

**Comment by adriweb** [comment]
Since I work on C++<->Lua integration on a daily basis at work, I feel like I would be inclined to think about some Lua(/LuaJIT) integration into CEmu.
After all, Lua is probably the most fitted language for scripting within that kind of host.
https://github.com/ThePhD/sol2 looks interesting to provide a nice C++ wrapper.

Ideally, the main core functions would be exposed, including debugging-related ones, and of course all of the GUI should be accessible programmatically too.
Once all that is "done", using Lua for scripting would supersede the JSON autotester files, for instance, right now relying on an array of semi-hardcoded actions to do the work (which works, but isn't as nice as it could be with proper scripting APIs built-in)

I'm assigning myself to this task, but oh well, I have no idea when I'm going to work on that. CEmu might reach 3.0 by then :P

**Comment by adriweb** [comment]
For fun, I added a few lines here and there on a [with_lua branch](https://github.com/CE-Programming/CEmu/tree/with_lua) to get something to build (just on my machine ; it's very WIP).
The example code from Sol does work:
```cpp
sol::state lua;
int x = 0;
lua.set_function("beep", [&x]{ ++x; });
lua.script("beep()");
assert(x == 1);
```
I'll look into how to integrate LuaJIT, apparently it's not so hard to call an external makefile from within the .pro. Then, it would be a static lib to use.

Then of course, the big part will be what/where/how to bind Qt (+ core) methods properly.

**Comment by adriweb** [comment]
As one can see in the with_lua branch, I've started binding just a few things to try it out, and it seems to work okay so far:
![A little lua script](https://i.imgur.com/YjtrCQL.png)

**Comment by adriweb** [comment]
Let's just close that in favor of #252.
Reopen if needed...
