### ISSUE TITLE
A way to display the back buffer / second half of the VRAM in case of 8bpp

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#21]
When we're using double-buffering (so, in 8bpp mode), It'd be neat to be able to have a secondary display showing the other half of the VRAM, so as to be able to debug what's happening on the other buffer while the first is being shown on the [primary] LCD.

I guess a secondary LCDWidget in a popup would work? Or yet another dock (but created/destroyed dynamically)?

**Comment by MateoConLechuga** [comment]
Well, this would have to be done for *all* of the bpp modes to be right. But 8bpp at first would be just fine.

**Comment by jacobly0** [comment]
This should be done as a "screen view" that you can open multiple instances of and has options for each instance like address, bpp, bebo, and bepo.  These should be updated in real time like the screen currently is so that when dma is implemented, you can open an instance that shows the same thing as the screen, but updates while debugging.

**Comment by MateoConLechuga** [comment]
Cool, all these ideas have been implemented in commit 44553c0. Closing this issue :)
