### ISSUE TITLE
Impossible to set the calculator to French

### ISSUE THREAD

**Issue by Skiski** [CE-Programming/CEmu#302]
Hi,

I'm trying CEmu mainly to take screenshots for my students. And for that, I need to set the calculator to French.

I'm using the linux version of CEmu (1.2) on fedora 28 64bits.

I use a TI 83 CE to dump the ROM and I used tilp2 to send and get the files. The real calculator is set to French.

When I use my ROM, I've noticed that I cannot change the language to French in the menu of the calculator. Only English is available. I've also noticed that in the App menu, there are only the finance ones. I don't know if it's related, since the languages seems to be stored as apps.

I don't if there is a problem with my ROM, the linux version of CEmu, or tilp, or just that it's impossible.

Thanks.

**Comment by debrouxl** [comment]
"I used tilp2 to send and get the files": does that mean that you used CEmu's ROM dumper, which only dumps a small subset of the Flash memory, instead of TILP's built-in ROM dumper, which dumps the entire Flash memory ?
In TILP II 1.18 and the corresponding version of libticalcs, the ROM dumper is quite slow; now that we have more information about USB communication works on the TI-eZ80 series, in the next release, or the development version which can be built using https://ti-pla.net/tilpinst , the ROM dumper is much more efficient.

**Comment by mateoconlechuga** [comment]
The language setting is actually an application on the calculator. CEmu just dumps the bare minimum in order to create a functional calculator, which does not include this application. You must use the tilp option `Tools > Dump Rom` with a connected calculator in order to extract the application as well.

Hope this helps :)

**Comment by Skiski** [comment]
Your right, I used CEmu dumper. I never used tilp2 either, so I didn't know that the dumped rom would be better or even if it would work with CEmu.
Anyway, I dump a new ROM with tilp and it works great and I was able to set it to French.

Thanks for your help.
