### ISSUE TITLE
(again) screen bug

### ISSUE THREAD

**Issue by JaroslavN** [CE-Programming/CEmu#31]
little bug / glitch,
nothing very special.
so, i was trolling aroud on CEmu and when i shoosed scale: 400% the whole screen was a mess.
( i know how to fix "easy" ;) )
![schermopname 144](https://cloud.githubusercontent.com/assets/16990273/13203123/b9d1e56a-d8af-11e5-8925-95d44301b682.png)

(here fun glitch , 
![schermopname 147](https://cloud.githubusercontent.com/assets/16990273/13203135/3b326472-d8b0-11e5-8407-8822af375694.png)

**Comment by Runer112** [comment]
Perhaps someone more knowledgeable about Qt and the UI system could fix the behavior in that first image. I'm guessing it would involve figuring out the maximum size that the screen panel can expand to and not allowing changing to a zoom level that would exceed that.

The second one isn't a bug at all. That's expected behavior... kind of. It seems you found the RGB888 LCD test, which leaves that mode on when exiting back to the OS, making the OS look rather strange. Perhaps I should properly clean up after that test program ends.

**Comment by MateoConLechuga** [comment]
I'm labeling this as an external issue and not planning on fixing it anytime soon.
