### ISSUE TITLE
Screenshots/recordings should be affected by screen brightness

### ISSUE THREAD

**Issue by runer112** [CE-Programming/CEmu#326]
- [x] Screenshots
- [ ] APNG recordings

**Comment by adriweb** [comment]
Current implementation draws a [black layer with alpha on top of the raw image](https://github.com/CE-Programming/CEmu/blob/master/gui/qt/lcdwidget.cpp#L39-L43), and only the raw image is used for [screenshots](https://github.com/CE-Programming/CEmu/blob/master/gui/qt/lcdwidget.cpp#L91) and [captures](https://github.com/CE-Programming/CEmu/blob/master/gui/qt/lcdwidget.cpp#L158).

Potential solution: use the context painted images/bytes instead of the initial raw image?

**Comment by adriweb** [comment]
For screenshots, it's trivial, `LCDWidget::getImage()` should be:

```cpp
    QPixmap pixmap(size());
    render(&pixmap);
    return pixmap.toImage();
```
instead of
```cpp
    m_mutex.lock();
    QImage ret(m_image);
    m_mutex.unlock();
    return ret;
```

The problem is much harder if we want to fix that for APNG recordings, since `apng_add_frame` is called within `LCDWidget::draw`, and I don't think we want to (which may not be up to date at this point anyway, there is an event that's fired in it to update the widget later on)

**Comment by adriweb** [comment]
This is now working.
