### ISSUE TITLE
Edits to Program not being Updated

### ISSUE THREAD

**Issue by wein7145** [CE-Programming/CEmu#336]
Windows 10
CEmu v1.3

1. Any program created in Ti Connect CE sends perfectly fine the first time however any edits to the program are not being updated.  

2. After updating in Ti Connect in CEmu goto File Open edited program and it doesn't update the edits? 

*I tried to see if resend selected fixes the problem but it doesn't

*The workaround is to reset the calculator and goto file open the edited program for each edit

*Another workaround is do small edits in wabbitemu (CSE) but just check final versions in CEmu

**Comment by jacobly0** [comment]
I don't clearly understand your issue, and I can't help with TI Connect CE, but I'll note two things that may or may not be related:
1. If you `View Calculator Variables` in order to transfer a program _from_ CEmu while that program is currently open in the program editor, you will get an incorrectly sized program (so if you added stuff to the end it will look like an old file).
2. You have to be on the homescreen to transfer files _to_ CEmu.
