### ISSUE TITLE
Upload Python App

### ISSUE THREAD

**Issue by tvlad1234** [CE-Programming/CEmu#349]
Is there a way to upload the Python app to the calculator? I am using the feature/python branch. I've successfully dumped the TI83 Python Edition ROM, but I can't upload the python app.

**Comment by adriweb** [comment]
Nope, not currently. OS and apps transfers need more USB work.
To get the app, you'll want to dump your calc more "fully", using TiLP (latest version: https://ti-pla.net/tilpinst) instead of CEmu's dumper.

Also, the feature/python branch doesn't yet actually support the arm co-processor (used for Python on real calcs) even if it has arm core emulation code. It however has updated hardware emulation stuff like the new Flash.

**Comment by tvlad1234** [comment]
Is there a way to fully (and legally) extract the flash from the TI SmartView Software? I have a legal, valid license for it.

**Comment by adriweb** [comment]
Well, there still would be the same problem with it if you use CEmu's dumper and obviously TiLP wouldn't work on SmartView :)
(Also, TI's license forbids users to use the rom on a non-TI emulator anyway)

**Comment by adriweb** [comment]
Will be fixed by #25 which is well underway.
