### ISSUE TITLE
Screen dock not resizable

### ISSUE THREAD

**Issue by sdnjack** [CE-Programming/CEmu#380]
On a lower resolution screen (1366 x 768) the screen dock is too big to allow for the keypad dock to be placed underneath. I use CEmu as a teaching aid and would like it to look as much like a real calculator as possible. Since I can't resize the screen dock, I have to have the keypad dock next to the screen, which looks weird to the students. Ideally, you could create a "full calculator" dock that is resizable for this situation.
---------------------------------------------
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎9/‎18/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0
Hardware  HP Probook x360 11 G2 EE  
CEmu v1.3

**Comment by mateoconlechuga** [comment]
CEmu is currently undergoing a rewrite of the GUI with all the feedback we've had. This is a planned feature, and hopefully it turns out looking better, so stay tuned :)

**Comment by Stephan-P** [comment]
@sdnjack I've been using CEmu as a teaching aid for quite some years on a low-res laptop and it works just fine.
- Enable UI Edit mode
- Open the docks "Settings", "Keypad" and "Screen". Make sure to close the others.
- In "Settings" adjust the scale to 75% or 80% (I can't remember exactly. I'm on a hi-res laptop now.)
- Arrange the Keypad dock below the Screen dock. This may require some ultra precise positioning, but at some point it will snap itself below the Screen dock.) Do not mind that they are not of the same width at this point.
- Close the Settings dock so you're left with just the Screen and the Keypad snapped below it.
- Right Mouse Click the Screen and disable the UI edit mode
- Now carefully resize the CEmu window size so that Screen dock and Keypad dock are of the same width and align vertically
- Shut down CEmu and restart it again and Presto, there's your TI-84 CE-T emulator for classroom instructions
- Optionally attach the CEmu icon to the taskbar 

![image](https://user-images.githubusercontent.com/10008599/110664562-ccd63f00-81c7-11eb-81a1-9e8d4c03a776.png)

**Comment by sdnjack** [comment]
Thanks, that helps a lot. I didn't know about the scaling.

**Comment by johann-petrak** [comment]
Does not work for me at all - when dragging the screen/keypad, it can only get arranged to the side or so that it will replace it and they get arranged as tabs. 
No luck at all stacking them so they are both part of the same window
