### ISSUE TITLE
CEMU MacOS release No Mountable File Systsm

### ISSUE THREAD

**Issue by s-silver** [CE-Programming/CEmu#386]
Operating system: MacOSX 10.11.6
CEMU version: latest
Issue:
Attempting to mount the release disk image causes the following error: no mountable file systems.
![Screen Shot 2021-03-01 at 9 52 11 AM](https://user-images.githubusercontent.com/69227528/109538653-32625700-7a75-11eb-9e57-2529d2d65cd6.png)

It's probably because of the age of the operating system.

**Comment by adriweb** [comment]
Yes, your OS is too old. I could provide you with a suitable .dmg but it still wouldn't matter because the Qt version we use requires macOS 10.13 at least.

I don't have enough time right now to check if I can build with an older Qt, it might be possible, but still troublesome. 

Are you unable to update your OS?

**Comment by s-silver** [comment]
Sorry, my computer's too old. It's from early 2011, so El Capitan is the latest I can get. Would it be possible to either run the Win32 version under WINE (Which, by the way, the download link is broken for), or compile and run the Linux version in XQuartz?

**Comment by adriweb** [comment]
You could try running the win32 version with wine, yes. Let us know how that goes, hmm.

**Comment by jacobly0** [comment]
For nightly builds the MinGW download links under advanced should work ([32-bit](http://jacobly.com/CEmu/master/latest/CEmu32.exe) or [64-bit](http://jacobly.com/CEmu/master/latest/CEmu64.exe)) or you can just download the latest github release.
