### ISSUE TITLE
can you flash a TI-83 Premium CE rom to a TI-84 CE

### ISSUE THREAD

**Issue by boxtop312** [CE-Programming/CEmu#387]
I know this is dumb but is it possible to do because I want to be able to use a TI-83 Premium CE but I don't want to import one from France and would rather flash it to a TI-84 CE because it's cheaper

**Comment by adriweb** [comment]
Well, there are ways to do that (at least on some hardware revisions, I believe), but they are mostly non-public, especially since this is too close to being considered cheating by exams boards banning exact-math calculations (the 84+ doesn't have it, while the 83 Premium CE does).

Regardless, this is off-topic for CEmu.
