### ISSUE TITLE
"Send files to calc" won't accept certain valid filenames. 

### ISSUE THREAD

**Issue by Zaalan3** [CE-Programming/CEmu#436]
What's wrong, and with what software version?
---------------------------------------------
**Operating System:** Windows 10 
**CEmu version:** CEmu v2.0dev (git: d606eb3)
**Describe your issue:**  

When sending an appvar to CEmu with the variable name 'out/BANK', the variable in question won't actually be sent it being a valid filename. The same file with the variable name 'BANK' will send. 

What are the steps to reproduce this issue?
-------------------------------------------
1. Create an appvar with convbin with the variable name 'out/BANK'
2. Create an appvar from the same source file with the variable name 'BANK' 
3. Send both to CEmu and a physical calculator via TI-Connect
4. Both will show on the calculator, but only 'BANK' will show on CEmu 

Any logs, error output, screenshot, other comments...?
------------------------------------------------------
An example of a `/` being used fine on-calc. 
![](https://media.discordapp.net/attachments/741771284970733640/1031455224264654848/20221017_013427.jpg)

**Comment by adriweb** [comment]
So this is now confirmed to work on master, thanks to commit 31dff66743ac8d02c9850ceeac12da5b14616085 which fixed #463 and actually had the same root cause (the slash is fine).

![CleanShot 2024-07-09 at 14 17 00@2x](https://github.com/CE-Programming/CEmu/assets/660896/d91c4b29-5ff0-457e-bc56-4bf55dc86c35)
