### ISSUE TITLE
iOS: iPad Pro split view support

### ISSUE THREAD

**Issue by nafehshoaib** [CE-Programming/CEmu#86]

**Comment by MateoConLechuga** [comment]
A little more information please.

**Comment by adriweb** [comment]
Hm, there's no iPad support at all in the first place, though, so what do you mean, "split view support"?
We're aware that there are other emulators named "CEmu" (although different casing), are you sure this is the right one?

(But anyway, however, CEmu isn't designed for non-desktop usages)

**Comment by nafehshoaib** [comment]
Since we are using Qt, I was able to build it for iOS and it was able to run on the simulator and my iPad Pro. I was able to upload the ROM by first creating it with the Mac version and my actual calculator, and then putting it on iCloud Drive. Other than one additional error, everything seemed to be running as far as general usablitity goes. 

Split View is where two apps can run side-by-side on a newer iPad running >iOS 9. It would be a great enhancement since it would make it possible for users to use the calculator while also using something like a note-taking app.

**Comment by adriweb** [comment]
Well, I suppose an iPad Pro is pretty much like a computer screen size-wise, so I'm not that surprised the UI would fit reasonably well.
One thing, though (which is part of why no efforts have been made for non-desktop targets*), is that TI _really_ doesn't want CE emulators on non-desktop devices (for some reason, they're somewhat OK with Nspire ones though). *The other reason is that the primary goal of CEmu is to help CE developers by providing a well-featured debugging environment, and this can pretty much be done on computers only, especially since it goes well with what developers will use alongside:  program editors/IDE, C/ASM toolchain, etc.

Considering this target isn't something we're working on, I guess I'll close this as "wontfix".
_(Also, I believe I'm the only one among the main committers who has [limited] iOS dev experience, and I have no idea about split-screen APIs, it's been some time since I've messed with all that - it's probably a property to enable somewhere - maybe in Info.plist? Good luck anyway :))_
