### ISSUE TITLE
Incorrect keypad text sizes on Windows

### ISSUE THREAD

**Issue by Runer112** [CE-Programming/CEmu#89]
For windows, the current code tries to do some fancy DPI scaling stuff and fails. The code in question is found here: https://github.com/CE-Programming/CEmu/blob/85136dc5d8dcffa5e982ecda5a23500a86a86fec/gui/qt/keypad/keypadwidget.cpp#L108-L119

I believe that logcial DPI is the desired metric, not physical DPI. However, I don't really understand why this extra stuff was necessary in the first place, so I don't feel comfortable changing it. Non-Windows OSes don't even do anything special.

Also, why does Windows seem to have a base text size of 7, compared to 5 for other OSes?

Screenshot:
![size fail](https://i.imgur.com/jaCxBnc.png)

**Comment by JaroslavN** [comment]
how is this stuff programmed ,,in pieces or like : §6(color) test(text), §3A or in pieces?
still a nice program

**Comment by adriweb** [comment]
You can see by yourself right here: https://github.com/CE-Programming/CEmu/blob/master/gui/qt/keypad/keypadwidget.cpp

**Comment by JaroslavN** [comment]
yes , it's in one line but pieces... and this happend too 
![schermopname 35](https://cloud.githubusercontent.com/assets/16990273/19626819/4b77477c-9939-11e6-8f48-998a9d4c5aa9.png)

**Comment by adriweb** [comment]
Yes, that's basically the same problem as @Runer112.
Forcing the size to 6, for instance, works, and maybe messing with the DPI too - we haven't really found a good solution yet.

**Comment by alberthdev** [comment]
On VirtualBox, this problem exists too (interesting DPI settings, for sure):
![image](https://cloud.githubusercontent.com/assets/1274384/19635725/57a3f28a-9992-11e6-92fe-e07b5b98c74d.png)

I did some hunting, and it looks like (according to [QTBUG-50698](https://bugreports.qt.io/browse/QTBUG-50698)) the suggested solution is to use `Qt::AA_EnableHighDpiScaling`. According to the documentation:

> Enables high-DPI scaling in Qt on supported platforms (see also High DPI Displays). Supported platforms are X11, Windows and Android. Enabling makes Qt scale the main (device independent) coordinate system according to display scale factors provided by the operating system. This corresponds to setting the QT_AUTO_SCREEN_SCALE_FACTOR environment variable to 1. This value has been added in Qt 5.6. This attribute must be set before Q(Gui)Application is constructed.

I attempted to try this method of DPI scaling, and have this:
![image](https://cloud.githubusercontent.com/assets/1274384/19636682/d2a7366c-9998-11e6-91f5-8737a694a262.png)

Of course, since this is VirtualBox, it's hard to tell if this actually worked! For those who have high-DPI screens, could you please confirm that this scales correctly (or incorrectly)?

Test binaries are available [here](https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git-test/201610/20161024/cemu-20161024_073658-git-608bd0a/). Relevant changes are [here](https://github.com/alberthdev/CEmu/commit/7b87952f5a43cc49f51f1a5e448315911ae1c7ac).

**Comment by adriweb** [comment]
Nice :)

**Comment by adriweb** [comment]
Well, tried it on my Win10 VM, it looks the same as before, so I guess it at least didn't break anything on environment where it was working before.

**Comment by Runer112** [comment]
@alberthdev Your fixed binary has indeed fixed the issue on my Windows OS. But it would probably be nice if we had the people who designed the virtual keypadto verify the font metrics; @MateoConLechuga, @jacobly0? For one, I never understood why the label font is "semi-condensed" on non-Windows OSes.

**Comment by MateoConLechuga** [comment]
Works a lot better for me as well; the manual computation in keypadwidget.cpp is no longer necessary and can instead use exactly the same code as linux and macOS. These lines work best:

Change to lines 108-119
```
    font.setBold(true);
    font.setPixelSize(5);
#ifndef Q_WS_WIN
    font.setStretch(QFont::SemiCondensed);
#endif
```

Change to lines 134-138
```
    if (is83) {
        m_config.secondFont.setStretch(QFont::Condensed);
    }
```

**Comment by adriweb** [comment]
Yeah, and the following part can be removed, apparently. Especially since it wasn't there on other OSes anyway:
```c
    if (is83) {
#ifndef _WIN32
        m_config.secondFont.setStretch(QFont::Condensed);
#endif
    }
```

**Comment by alberthdev** [comment]
Done - all changes applied: [related commit](https://github.com/alberthdev/CEmu/commit/f19503c37f7a42bc8edcc9a1c85992a0a97cb625), [new test build](https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git-test/201610/20161025/cemu-20161025_004424-git-5f5db07/)

For all Windows users - please test the new build out! (Especially if you have a high-DPI screen!)

**Comment by alberthdev** [comment]
Re-added black weight setting, since it looks better on Windows.

[Commit](https://github.com/alberthdev/CEmu/commit/057c39c1a77018eb32cf4f43e896eb3f28495e84) and [latest test build](https://oss.jfrog.org/artifactory/oss-snapshot-local/org/github/alberthdev/cemu/git-test/201610/20161025/cemu-20161025_023237-git-b5d48d4/)
