### ISSUE TITLE
See what we are typing on the screen ?

### ISSUE THREAD

**Issue by pythagogore** [CE-Programming/CEmu#97]
Hello.
This is a great software. No problem with the last version.
Is it possible to add the option wich would enable us to see on the screen computer what we are typing on the calculator in order as with TI-smatview.
Thank you

**Comment by adriweb** [comment]
Pasting some IRC log here:

>12:56:07 <@Adriweb> Possible, through some kind of raw list or something, but it won't be near as fancy as what SV does
>12:57:07 <@Adriweb> Though there's no history right now, not even an internal one
>12:57:16 <@Adriweb> So meh
>12:58:19 <@Adriweb> Also it's getting hard to add GUI elements :P
>12:59:16 <@Adriweb> Filling some history variable on the fly would probably be easy enough with lua
>12:59:21 <@Adriweb> Once events are added
>12:59:33 <@Adriweb> Then a var dump...
>12:59:49 <@Adriweb> This avoids GUI issues at least.

So, it's not a planned feature right now, especially since there are more important things to take care of on the emulation side first, but if this gathers enough interest (there might be developer usecases for it...), it would probably be rather easy to do it with Lua once it gets integrated. No ETA though.
